### PR TITLE
WIP: restructure CI test infra

### PR DESCRIPTION
**Pull request by bacongobbler**
This restructures kashti's test infrastructure to:

1. run the test suite on new pull requests (or for `brig run` when testing)
2. build the kashti container image using ACR build

This has not been tested yet, just posting it for other's enjoyment at this stage.

TODO:

- [ ] manually test this pipeline
- [ ] get this hosted on our production brigade instance
- [ ] restore building/pushing the image to DockerHub. We may need to drop back down to `docker` to do that step, but I'll ask around how others (read: brigade itself) are pushing and releasing images.

### CODE REVIEW

**Comment by bacongobbler** [comment]
closing for now while testing locally; will re-open once this is ready for review.

**Comment by bacongobbler** [comment]
currently blocked on https://github.com/Azure/azure-cli/issues/7011

**Comment by radu-matei** [comment]
🎉 
Do you think we can have this merged so at least we can build, test and lint?

**Comment by bacongobbler** [comment]
For sure!

**Pull request closed without merging**
