### PR TITLE
use kebab case for models

### LINKED ISSUE #193: Inconsistency in file names in the models folder
There is inconsistency in the file names under `models/` - all files here are capitalized, whereas all other files are not.

@flynnduism - is there a reason for it, or can we simply rename the files under `models/` and update all imports?

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #193

### CODE REVIEW

**Comment by flynnduism** [comment]
Some conflicts since BuildLog was added, rebase required though @bacongobbler

**Comment by bacongobbler** [comment]
Do we wanna hold off on this until #198? I can rebase off master and PR if you wanna push that one through.

**Comment by flynnduism** [comment]
@bacongobbler nice to get this in before that one if we can

**Comment by bacongobbler** [comment]
ok! I'll go ahead and rebase this.

**Comment by bacongobbler** [comment]
rebased

**Pull request merged**
