### PR TITLE
[WIP] Add project page

### PR DESCRIPTION
**Pull request by flynnduism**
* adds a project component
* ports markup and styles from 0.1.x
* add static content for page layout work
* configures the router for a static /project view

For #121, #138 . To tie into the work @seanknox has been doing on #139

### CODE REVIEW

**Comment by flynnduism** [comment]
Styling for the project builds is in place, and I've hooked up routing for `project/:id`. 

project-state-template


@seanknox - however I need help getting the component to properly consume and display the mock API data, currently throwing errors when I replicate how the dashboard component does it.

**Comment by flynnduism** [comment]
@seanknox I've updated the mock API format as discussed - as you predicted there's a cli error:

```
ERROR in src/app/mock-projects.ts(37,5): error TS2322: Type '{ project: { id: string; name: string; lastBuild: { id: string; project_id: string; type: string;...' is not assignable to type 'Project[]'.
  Type '{ project: { id: string; name: string; lastBuild: { id: string; project_id: string; type: string;...' is not assignable to type 'Project'.
    Object literal may only specify known properties, and 'project' does not exist in type 'Project'.
```

Does the [project.ts](https://github.com/Azure/kashti/blob/angular5/src/app/models/project.ts) need to adapt to the new format too?

**Comment by seanknox** [comment]
@flynnduism This is nearly complete and getting to be a big changeset—I recommend we merge as is. Dynamic data, both mock or from https://cors-anywhere.herokuapp.com/http://acid-api.technosophos.me:7745 is working. The last thing to fix is the build status logic so that correct status is displayed (e.g. running, success, failed, unknown). I've started work on that to extract to a badge status component that I'll continue on in a new issue. Here's what the page looks like now:

kashti

**Comment by seanknox** [comment]
Left to do:
- badge status on project page
- fix and add tests (i was bad)
- fix linting errors

I'll create a new issue to capture this work and assign to myself.

**Comment by flynnduism** [comment]
Awesome work Sean. Tested it out locally, it's a big step forward!

Merging

**Pull request merged**
